// GENERATED BY tool, DO NOT MODIFY BY HAND
import 'package:flutter/widgets.dart';

class AntIcons {
  static const _fontFamily = 'AntDesignMobile';
  static const _fontPackage = 'antd_mobile';
  static const aaOutline =
      IconData(59648, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const addCircleOutline =
      IconData(59649, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const addOutline =
      IconData(59650, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const addressBookFill =
      IconData(59651, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const addSquareOutline =
      IconData(59652, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const alipayCircleFill =
      IconData(59653, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const alipaySquareFill =
      IconData(59654, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const antOutline =
      IconData(59655, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const appOutline =
      IconData(59656, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const appstoreOutline =
      IconData(59657, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const arrowDownCircleOutline =
      IconData(59658, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const arrowsAltOutline =
      IconData(59659, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const audioFill =
      IconData(59660, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const audioMutedOutline =
      IconData(59661, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const audioOutline =
      IconData(59662, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const bankcardOutline =
      IconData(59663, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const bellMuteOutline =
      IconData(59664, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const bellOutline =
      IconData(59665, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const billOutline =
      IconData(59666, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const calculatorOutline =
      IconData(59667, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const calendarOutline =
      IconData(59668, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const cameraOutline =
      IconData(59669, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const chatAddOutline =
      IconData(59670, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const chatCheckOutline =
      IconData(59671, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const chatWrongOutline =
      IconData(59672, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const checkCircleFill =
      IconData(59673, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const checkCircleOutline =
      IconData(59674, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const checkOutline =
      IconData(59675, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const checkShieldFill =
      IconData(59676, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const checkShieldOutline =
      IconData(59677, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const clockCircleFill =
      IconData(59678, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const clockCircleOutline =
      IconData(59679, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const closeCircleFill =
      IconData(59680, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const closeCircleOutline =
      IconData(59681, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const closeOutline =
      IconData(59682, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const closeShieldOutline =
      IconData(59683, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const collectMoneyOutline =
      IconData(59684, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const compassOutline =
      IconData(59685, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const contentOutline =
      IconData(59686, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const couponOutline =
      IconData(59687, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const deleteOutline =
      IconData(59688, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const downCircleOutline =
      IconData(59689, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const downFill =
      IconData(59690, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const downlandOutline =
      IconData(59691, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const downOutline =
      IconData(59692, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const editFill =
      IconData(59693, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const editSFill =
      IconData(59694, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const editSOutline =
      IconData(59695, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const environmentOutline =
      IconData(59696, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const exclamationCircleFill =
      IconData(59697, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const exclamationCircleOutline =
      IconData(59698, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const exclamationOutline =
      IconData(59699, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const exclamationShieldFill =
      IconData(59700, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const exclamationShieldOutline =
      IconData(59701, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const exclamationTriangleOutline =
      IconData(59702, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const eyeFill =
      IconData(59703, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const eyeInvisibleFill =
      IconData(59704, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const eyeInvisibleOutline =
      IconData(59705, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const eyeOutline =
      IconData(59706, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const faceRecognitionOutline =
      IconData(59707, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const fileOutline =
      IconData(59708, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const fileWrongOutline =
      IconData(59709, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const fillinOutline =
      IconData(59710, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const filterOutline =
      IconData(59711, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const fingerdownOutline =
      IconData(59712, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const fireFill =
      IconData(59713, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const flagOutline =
      IconData(59714, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const folderOutline =
      IconData(59715, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const forbidFill =
      IconData(59716, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const frownFill =
      IconData(59717, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const frownOutline =
      IconData(59718, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const giftOutline =
      IconData(59719, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const globalOutline =
      IconData(59720, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const handPayCircleOutline =
      IconData(59721, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const heartFill =
      IconData(59722, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const heartOutline =
      IconData(59723, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const histogramOutline =
      IconData(59724, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const informationCircleFill =
      IconData(59725, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const informationCircleOutline =
      IconData(59726, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const keyOutline =
      IconData(59727, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const koubeiFill =
      IconData(59728, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const koubeiOutline =
      IconData(59729, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const leftOutline =
      IconData(59730, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const likeOutline =
      IconData(59731, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const linkOutline =
      IconData(59732, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const locationFill =
      IconData(59733, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const locationOutline =
      IconData(59734, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const lockFill =
      IconData(59735, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const lockOutline =
      IconData(59736, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const loopOutline =
      IconData(59737, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const mailFill =
      IconData(59738, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const mailOpenOutline =
      IconData(59739, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const mailOutline =
      IconData(59740, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const messageFill =
      IconData(59741, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const messageOutline =
      IconData(59742, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const minusCircleOutline =
      IconData(59743, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const minusOutline =
      IconData(59744, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const moreOutline =
      IconData(59745, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const movieOutline =
      IconData(59746, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const payCircleOutline =
      IconData(59747, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const phonebookFill =
      IconData(59748, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const phonebookOutline =
      IconData(59749, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const phoneFill =
      IconData(59750, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const pictureOutline =
      IconData(59751, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const picturesOutline =
      IconData(59752, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const pictureWrongOutline =
      IconData(59753, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const pieOutline =
      IconData(59754, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const playOutline =
      IconData(59755, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const questionCircleFill =
      IconData(59756, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const questionCircleOutline =
      IconData(59757, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const receiptOutline =
      IconData(59758, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const receivePaymentOutline =
      IconData(59759, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const redoOutline =
      IconData(59760, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const rightOutline =
      IconData(59761, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const scanCodeOutline =
      IconData(59762, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const scanningFaceOutline =
      IconData(59763, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const scanningOutline =
      IconData(59764, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const searchOutline =
      IconData(59765, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const sendOutline =
      IconData(59766, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const setOutline =
      IconData(59767, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const shopbagOutline =
      IconData(59768, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const shrinkOutline =
      IconData(59769, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const smileFill =
      IconData(59770, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const smileOutline =
      IconData(59771, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const soundMuteFill =
      IconData(59772, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const soundMuteOutline =
      IconData(59773, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const soundOutline =
      IconData(59774, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const starFill =
      IconData(59775, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const starOutline =
      IconData(59776, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const stopOutline =
      IconData(59777, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const systemQRcodeOutline =
      IconData(59778, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const tagOutline =
      IconData(59779, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const teamFill =
      IconData(59780, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const teamOutline =
      IconData(59781, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const textDeletionOutline =
      IconData(59782, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const textOutline =
      IconData(59783, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const transportQRcodeOutline =
      IconData(59784, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const travelOutline =
      IconData(59785, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const truckOutline =
      IconData(59786, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const undoOutline =
      IconData(59787, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const unlockOutline =
      IconData(59788, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const unorderedListOutline =
      IconData(59789, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const upCircleOutline =
      IconData(59790, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const uploadOutline =
      IconData(59791, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const upOutline =
      IconData(59792, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const userAddOutline =
      IconData(59793, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const userCircleOutline =
      IconData(59794, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const userContactOutline =
      IconData(59795, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const userOutline =
      IconData(59796, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const userSetOutline =
      IconData(59797, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const videoOutline =
      IconData(59798, fontFamily: _fontFamily, fontPackage: _fontPackage);
}
