const { execSync } = require("child_process");
const fs = require("fs");
const _ = require("lodash");

fs.copyFileSync("dist/AntDesignMobile.ttf", "../fonts/AntDesignMobile.ttf");

const selection = require("./dist/selection.json");

let code = `// GENERATED BY tool, DO NOT MODIFY BY HAND
import 'package:flutter/widgets.dart';
class AntIcons {`;
let exampleCode = `// GENERATED BY tool, DO NOT MODIFY BY HAND
const iconsData = {`;

selection.icons.forEach(({ properties }) => {
  code += `static const IconData ${_.camelCase(properties.name)} = IconData(${
    properties.code
  }, fontFamily: "AntDesignMobile", fontPackage: "antd_mobile");`;
  exampleCode += `'${properties.name}': ${properties.code},`;
});

code += "}";
exampleCode += "};";

fs.writeFileSync("../lib/src/icons.dart", code);
fs.writeFileSync("../example/lib/icons_data.dart", exampleCode);

execSync("dart format ../lib/src/icons.dart ../example/lib/icons_data.dart");
